### PR TITLE
added Zazuko to sponsor data

### PR DESCRIPTION
**Pull request by tpluscode**
Not sure if you'd make them `HEAD` sponsor?

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@tpluscode they'll be a GET sponsor based on the prospectus and other sponsors. Also, I'd like to (soon) get all the sponsors aggregated to the home page.

Mind adjusting the data?

Also, you can remove the PUT sponsorship, as we didn't have one of those this year.

Thanks!

**Review by BigBlueHat — CHANGES_REQUESTED** [review]
See above. 😜

**Comment by tpluscode** [comment]
`HEAD` is also empty now. remove?

**Comment by BigBlueHat** [comment]
@tpluscode yeah, go ahead and remove HEAD from the `eu` data file since we didn't get a dedicated videographer sponsor. You can commit that one straight to master if you want.

**Pull request merged**
